In [1]:
import pandas as pd

# Read one csv file from URL with pandas

### Target website: https://www.football-data.co.uk/data.php

In [4]:
# reading the dataset using read_csv method
df_bundesliga = pd.read_csv("https://www.football-data.co.uk/mmz4281/2425/D1.csv")

In [5]:
# show the dataframe
df_bundesliga

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,D1,23/08/2024,19:30,M'gladbach,Leverkusen,2,3,A,0.0,2.0,...,1.86,2.04,1.87,2.06,1.96,2.08,1.91,1.96,1.91,2.07
1,D1,24/08/2024,14:30,Augsburg,Werder Bremen,2,2,D,2.0,1.0,...,1.88,2.05,1.88,2.04,1.88,2.06,1.86,2.03,1.90,2.10
2,D1,24/08/2024,14:30,Freiburg,Stuttgart,3,1,H,1.0,1.0,...,1.95,1.98,1.95,1.97,1.98,2.09,1.87,2.00,1.95,2.04
3,D1,24/08/2024,14:30,Hoffenheim,Holstein Kiel,3,2,H,2.0,0.0,...,2.03,1.90,1.99,1.93,2.16,1.95,2.02,1.86,2.00,1.95
4,D1,24/08/2024,14:30,Mainz,Union Berlin,1,1,D,0.0,0.0,...,2.10,1.83,2.11,1.83,2.13,1.85,2.07,1.81,2.18,1.84
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
301,D1,17/05/2025,14:30,Hoffenheim,Bayern Munich,0,4,A,0.0,1.0,...,1.75,2.05,1.81,2.09,1.87,2.13,1.82,2.02,1.92,2.06
302,D1,17/05/2025,14:30,Mainz,Leverkusen,2,2,D,1.0,0.0,...,1.86,2.04,1.89,2.03,1.90,2.08,1.86,2.03,1.85,2.16
303,D1,17/05/2025,14:30,M'gladbach,Wolfsburg,0,1,A,0.0,0.0,...,2.04,1.86,2.03,1.88,2.04,1.90,2.01,1.85,2.07,1.90
304,D1,17/05/2025,14:30,RB Leipzig,Stuttgart,2,3,A,2.0,1.0,...,1.91,1.99,1.92,2.01,1.98,2.03,1.92,1.93,2.04,1.94
305,D1,17/05/2025,14:30,St Pauli,Bochum,0,2,A,0.0,1.0,...,1.97,1.93,1.98,1.94,1.98,1.97,1.93,1.92,1.99,1.99

In [6]:
# rename some columns to understand better the dataframe
df_bundesliga.rename(columns={"FTHG": "home_goals",
                              "FTAG": "away_goals"}, inplace=True)

In [8]:
# we use columns attribute to get the names of columns
df_bundesliga.columns

Index(['Div', 'Date', 'Time', 'HomeTeam', 'AwayTeam', 'home_goals',
       'away_goals', 'FTR', 'HTHG', 'HTAG',
       ...
       'B365CAHH', 'B365CAHA', 'PCAHH', 'PCAHA', 'MaxCAHH', 'MaxCAHA',
       'AvgCAHH', 'AvgCAHA', 'BFECAHH', 'BFECAHA'],
      dtype='object', length=119)

In [11]:
# get the shape of dataframe (row, columns)
df_bundesliga.shape

(306, 119)

In [ ]:
print("gfsgh")